<a href="https://colab.research.google.com/github/TriBot2o/AI_And_ML_Year3/blob/main/Worksheet_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Version Check

In [ ]:
import sys
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello,World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello,World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


# Data types in Python


In [ ]:
# mutable data type (eg:List)
my_list = [1,2,3]
print("Original list:", my_list)

# modify the list by changing its content
my_list.append(4)
print("Modified list :", my_list)

# immutable datatype (eg:Tuple)
my_tuple = (1,2,3)
print("original tuple: ", my_tuple)

# here you will get an AttributeError
# my_tuple.append(4)

Original list: [1, 2, 3]
Modified list : [1, 2, 3, 4]
original tuple:  (1, 2, 3)


## Some common data types in Python

### Numeric

In [ ]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age =", type(age))
print("data type of variable pi =", type(pi))
print("data type of variable temperature =", type(temperature))

data type of variable age = <class 'int'>
data type of variable pi = <class 'float'>
data type of variable temperature = <class 'float'>


### Sequence

In [ ]:
# string : it is a sequence of characters enclosed ni double or single quote
# it is an immutable sequence
name = "aliec"
greeting = 'hello'
address = "123 Main st"
print("data type of the variable name: ",type(name))
print("data type of the variable greeting: ",type(greeting))
print("data type of the variable address: ",type(address))

# slice only one element
print("first element of name: ",name[0])
print("last element of name: ", name[-1])

#slice a range of elements
print("the second letter to the fourth of the name is:", name[1:4])
print("the first teo letters of the namme are:", name[:2])
print("substring starting from the third letter is:", name[2:])

data type of the variable name:  <class 'str'>
data type of the variable greeting:  <class 'str'>
data type of the variable address:  <class 'str'>
first element of name:  a
last element of name:  c
the second letter to the fourth of the name is: lie
the first teo letters of the namme are: al
substring starting from the third letter is: iec


In [ ]:
# list : it is are sequence that can contains mizxed data types and are mutable
list1 = [1,2,3,4]
mixed_list = [12,"hello", True]
print(mixed_list)
mixed_list[0] = False
mixed_list

[12, 'hello', True]


[False, 'hello', True]

In [ ]:
#tuple : these are ordered and immutable collections
colors = ('red', 'green', 'yellow', 'blue')
print("first element: ",colors[0])
print("last two element: ",colors[2:])
print("middle two element: ",colors[1:3])
#you will get a typeError if you try to change it
#colors[0] = 'purple'
colors

first element:  red
last two element:  ('yellow', 'blue')
middle two element:  ('green', 'yellow')


('red', 'green', 'yellow', 'blue')

### Mapping

In [ ]:
# this  catagory incudes datatypes that store data in key and value pairs

# dic : Represents dictionaries, which can store various data types as values associated with unique keys

person = {'name':'John','age':30,'cit':'Pittsburgh'}
print(f"hello my name is {person['name']}. I am {person['age']} years old and i live at {person['cit']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

hello my name is John. I am 30 years old and i live at Pittsburgh.
All keys: ['name', 'age', 'cit']
All values: ['John', 30, 'Pittsburgh']


### Set

In [ ]:
#these are unordered collections of unique elements.
#They are useful for membership testing and eliminating duplicate entries.
# these us also an immutable version of set called frozenset

unique_numbers = {1,2,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


### Boolean

In [ ]:
is_student = True
has_licence = False
print('datatype of the variable is_student is ',type(is_student))
print('datatype of the variable has_licence is ',type(has_licence))

datatype of the variable is_student is  <class 'bool'>
datatype of the variable has_licence is  <class 'bool'>


### Special


In [ ]:
# This category is used for unique data types that do not fit into the other categories.

#NoneType: Represents the absence of a value or a null value
result = None

# Logical Statements and Loops

### Logical Statements

In [ ]:
# if, elif and else conditional operations
num = 10
if num > 0:
  print("Positive")
elif num == 0:
  print("Zero")
else:
  print("Negative")

Positive


In [ ]:
# Comparision operators like the name suggests compares values

x = 5
y = 10
if x > 0 and y < 20:
  print("both conditions are true")
if x > 0 or y > 20:
  print("at least one condition is true")
if not x == 0:
  print(" x is not equal to 0")

both conditions are true
at least one condition is true
 x is not equal to 0


In [ ]:
# Logical operators they are used to combine multiple conditions

a = True
b = False
if a and b:
  print("both are true")
else:
  print("either a or b is false")
if a or b:
  print("at least one is true")
else:
  print("both are false")
if not a:
  print("a is false")
else:
  print("a is true")

either a or b is false
at least one is true
a is true


### Loops

In [ ]:
#for loop
fruits = ["apple","banana","cherry"]
for fruit in fruits:
  print(fruit)

#while loop
count = 0
while count < 5:
  print("Count is: ",count)
  count += 1

#break
fruits = ["apple","banana","orange"]
print("Loop 1")
for fruit in fruits:
  print(fruit)
  if fruit == "apple":
    break
#continue
print("Loop 2")
for fruit in fruits:
  if fruit == "apple":
    continue
  else:
    print(fruit)

apple
banana
cherry
Count is:  0
Count is:  1
Count is:  2
Count is:  3
Count is:  4
Loop 1
apple
Loop 2
banana
orange


# Functions

In [ ]:
def add_binary(a,b):
  '''
  Returns the sum of teo decimal numbers in binary digits.

  Parameters:
  a (int): The first decimal number.
  b (int): The second decimal number.

  Returns:
  binary_sum (str): Biary string of the sum of a and b.
  '''
  binary_sum = bin(a+b)[2:]
  return binary_sum

x=2
y=3
print(add_binary(x,y))

101


In [ ]:
# Built in functions
print("Hello world!")
length = len("Hello")
data_type = type(42)
total = sum([1,2,3])
print(length)
print(data_type)
print(total)

Hello world!
5
<class 'int'>
6


In [ ]:
# Build in Methods
message = "hello".upper()
fruits = ["appke", "banana"]
fruits.append("cherry")
info = {"name":"Alice","age":25}
age = info.get("age")
print(message)
print(fruits)
print(age)

HELLO
['appke', 'banana', 'cherry']
25


In [ ]:
# User defined functions
def temperature_converter():
  '''
  Converets temperature between Celcius and Fajrenheit.

  This function prompts the user to specify the conversion type (Celsius to Fahrenheit or Fahrenheit to Celsius)
  and then asks for the temperature value. It calculates and returns the converted temperature.

  Returns:
  float: The converted temperature value.
  '''

  print("Choose the conversion type")
  print("1. Celsius to Fahrenheit")
  print("2. Fahrenheit to Celsius")
  choice = input ("Enter 1 or 2: ")
  if choice == "1":
    celsius = float(input("Enter the temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}C is equal to {fahrenheit}F.")
  elif choice == "2":
    fahrenheit = float(input("Enter the temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print(f"{fahrenheit}F is equal to {celsius}C")
  else:
    print("Invalid choice. Please enter 1 or 2.")

temperature_converter()

Choose the conversion type
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 1
Enter the temperature in Celsius: 26
26.0C is equal to 78.8F.


## GLobal and Local Variable

In [ ]:
# global variable

x = 10 # global variable
def print_global():
  print(x)

print_global()
print(x)

10
10


In [ ]:
#Local varibale
def print_local():
  y = 5 # local variable
  print(y)

print_local()
print(y)

5
3


In [ ]:
# Accesssing anf modifing global variable inside a function

x = 10 #global variable
def modify_global():
  global x # to mmodify the global variable in a function you need the global keyword
  x = 20 # modify the global variable
modify_global()
print(x)

20


# To Do Task

## Task-1

### Exercise on Functions

In [1]:
# Create a Python program that converts between different units of measurement.

def meter_to_feet(a):
    """
    Converts meters to feet.

    Parameters:
    a (float): The length in meters to be converted.

    Returns:
    float: The length in feet.
    """
    return a * 3.28084

def feet_to_meter(a):
    """
    Converts feet to meters.

    Parameters:
    a (float): The length in feet to be converted.

    Returns:
    float: The length in meter.
    """
    return a / 3.28084

def kilograms_to_pounds(a):
    """
    Converts kilograms to pounds.

    Parameters:
    a (float): The weight in kilograms to be converted.

    Returns:
    float: The weight in pounds.
    """
    return a * 2.20462

def pounds_to_kilograms(a):
    """
    Converts pounds to kilograms.

    Parameters:
    a (float): The weight in pounds to be converted.

    Returns:
    float: The weight in kilograms.
    """
    return a / 2.20462

def liters_to_gallons(a):
    """
    Converts liters to gallons.

    Parameters:
    a (float): The volume in liters to be converted.

    Returns:
    float: The volume in gallons.
    """
    return a * 0.264172

def gallons_to_liters(a):
    """
    Converts gallons to liters.
    Parameters:
    a (float): The volume in gallons to be converted.

    Returns:
    float: The volume in liters.
    """
    return a / 0.264172

choice = 0
while choice != 4:
  print("\nChoose the conversion type")
  print("1. Length( m to ft / ft to m )")
  print("2. Mass( kg to lb / lb to kg )")
  print("3. Volume( l to g / g to l )")
  print("4. Exit")

  try:
        choice = int(input("Enter your choice: "))
        if choice < 1 or choice > 4:
            print("Invalid! Please select a number between 1 and 4.")
            continue

        if choice == 1:
            print("\n1. Meter to Feet")
            print("2. Feet to Meter")
            sub_choice = int(input("Enter your choice: "))

            if sub_choice == 1:
                val = float(input("Enter meters: "))
                print(f"{val}m is equal to {meter_to_feet(val):.2f}ft.")
            elif sub_choice == 2:
                val = float(input("Enter feet: "))
                print(f"{val}ft is equal to {feet_to_meter(val):.2f}m.")
            else:
                print("Invalid sub-choice selection.")

        elif choice == 2:
            print("\n1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = int(input("Enter your choice: "))

            if sub_choice == 1:
                val = float(input("Enter kilograms: "))
                print(f"{val}kg is equal to {kilograms_to_pounds(val):.2f}lbs.")
            elif sub_choice == 2:
                val = float(input("Enter pounds: "))
                print(f"{val}lbs is equal to {pounds_to_kilograms(val):.2f}kg.")
            else:
                print("Invalid sub-choice selection.")

        elif choice == 3:
            print("\n1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = int(input("Enter your choice: "))

            if sub_choice == 1:
                val = float(input("Enter liters: "))
                print(f"{val}L is equal to {liters_to_gallons(val):.2f}gal.")
            elif sub_choice == 2:
                val = float(input("Enter gallons: "))
                print(f"{val}gal is equal to {gallons_to_liters(val):.2f}L.")
            else:
                print("Invalid sub-choice selection.")

        elif choice == 4:
            print("Goodbye!")

  except ValueError:
    print("\nError: Please enter a valid numeric value.")



Choose the conversion type
1. Length( m to ft / ft to m )
2. Mass( kg to lb / lb to kg )
3. Volume( l to g / g to l )
4. Exit
Enter your choice: sfs

Error: Please enter a valid numeric value.

Choose the conversion type
1. Length( m to ft / ft to m )
2. Mass( kg to lb / lb to kg )
3. Volume( l to g / g to l )
4. Exit
Enter your choice: 5
Invalid! Please select a number between 1 and 4.

Choose the conversion type
1. Length( m to ft / ft to m )
2. Mass( kg to lb / lb to kg )
3. Volume( l to g / g to l )
4. Exit
Enter your choice: 1

1. Meter to Feet
2. Feet to Meter
Enter your choice: 3
Invalid sub-choice selection.

Choose the conversion type
1. Length( m to ft / ft to m )
2. Mass( kg to lb / lb to kg )
3. Volume( l to g / g to l )
4. Exit
Enter your choice: 1

1. Meter to Feet
2. Feet to Meter
Enter your choice: ss

Error: Please enter a valid numeric value.

Choose the conversion type
1. Length( m to ft / ft to m )
2. Mass( kg to lb / lb to kg )
3. Volume( l to g / g to l )
4. Exit

## Task-2

In [4]:
def find_sum(numbers):
    """
    Calculates the total sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values (floats/ints).

    Returns:
    float: The sum of all numbers in the list.
    """
    return sum(numbers)

def find_average(numbers):
    """
    Calculates the average  of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average value.
    """
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Finds the largest number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum value found.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the smallest number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum value found.
    """
    return min(numbers)

choice = 0
while choice != 5:
    print("\nWhat do you want to do?")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")
    print("5. Exit")

    try:
        choice = int(input("Enter your choice : "))

        if choice < 1 or choice > 5:
            print("Invalid! Please select a number between 1 and 5.")
            continue

        if choice == 5:
            print("Goodbye!")
            break

        user_input = input("Enter numbers separated by spaces (e.g., 10 2.5 30): ")
        num_list = [float(x) for x in user_input.split()]

        if len(num_list) == 0:
            print("Error: The list cannot be empty.")
            continue

        if choice == 1:
            print(f"The Total Sum is: {find_sum(num_list)}")

        elif choice == 2:
            print(f"The Average is: {find_average(num_list):.2f}")

        elif choice == 3:
            print(f"The Maximum value is: {find_maximum(num_list)}")

        elif choice == 4:
            print(f"The Minimum value is: {find_minimum(num_list)}")

    except ValueError:
        print("\nError: Invalid input. Please enter numbers only.")
    except Exception as e:
        print(f"\nAn unexpected error occurred: {e}")


What do you want to do?
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
5. Exit
Enter your choice : hj

Error: Invalid input. Please enter numbers only.

What do you want to do?
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
5. Exit
Enter your choice : 9
Invalid! Please select a number between 1 and 5.

What do you want to do?
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
5. Exit
Enter your choice : 1
Enter numbers separated by spaces (e.g., 10 2.5 30): 
Error: The list cannot be empty.

What do you want to do?
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
5. Exit
Enter your choice : 1
Enter numbers separated by spaces (e.g., 10 2.5 30): saf

Error: Invalid input. Please enter numbers only.

What do you want to do?
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
5. Exit
Enter your choice : 1
Enter numbers separated by spaces (e.g., 10 2.5 30): 1212
The Total Sum is: 1212.0

What do you want to do?
1. Find Sum
2. Find Ave

### Exercise on List Manipulation

In [5]:
def extract_every_other(lst):
    """
    Extracts every other element from a list starting from the first element.

    Parameters:
    lst (list): The original list of elements.

    Returns:
    list: A new list containing elements at indices 0, 2, 4, etc.
    """
    # [::2] means start at the beginning, go to the end, with a step of 2
    return lst[::2]

original_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(original_list)

print(f"Original List: {original_list}")
print(f"Extracted List: {result}")

Original List: [1, 2, 3, 4, 5, 6]
Extracted List: [1, 3, 5]


In [6]:
def get_sublist(lst, start, end):
    """
    Extracts a sublist from a given list from start to end index (inclusive).

    Parameters:
    lst (list): The original list of elements.
    start (int): The starting index.
    end (int): The ending index.

    Returns:
    list: A new list containing elements from start index to end index.
    """
    # We use end + 1 because Python slices are exclusive of the stop index
    return lst[start:end+1]

my_list = [1, 2, 3, 4, 5, 6]
start_idx = 2
end_idx = 4

result = get_sublist(my_list, start_idx, end_idx)
print(f"Sublist from index {start_idx} to {end_idx}: {result}")

Sublist from index 2 to 4: [3, 4, 5]


In [7]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The original list of elements.

    Returns:
    list: A new list with the elements in reverse order.
    """
    # [::-1] means start from the end and move backwards with a step of -1
    return lst[::-1]

my_list = [1, 2, 3, 4, 5]
reversed_result = reverse_list(my_list)

print(f"Original: {my_list}")
print(f"Reversed: {reversed_result}")

Original: [1, 2, 3, 4, 5]
Reversed: [5, 4, 3, 2, 1]


In [8]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list using slicing.

    Parameters:
    lst (list): The original list of elements.

    Returns:
    list: A new list excluding the first and last elements.
    """
    # Slice from index 1 up to (but not including) the last index -1
    return lst[1:-1]

my_list = [1, 2, 3, 4, 5]
trimmed_list = remove_first_last(my_list)

print(f"Original: {my_list}")
print(f"Trimmed: {trimmed_list}")

Original: [1, 2, 3, 4, 5]
Trimmed: [2, 3, 4]


In [9]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list using slicing.

    Parameters:
    lst (list): The original list of elements.
    n (int): The number of elements to extract from the start.

    Returns:
    list: A new list containing the first n elements.
    """
    # Slice from the start up to index n (exclusive)
    return lst[:n]

my_list = [1, 2, 3, 4, 5]
n_value = 3
result = get_first_n(my_list, n_value)

print(f"Original: {my_list}")
print(f"First {n_value} elements: {result}")

Original: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


In [11]:
def get_last_n(lst, n):
    """
    Extracts the last n elements from a list using negative slicing.

    Parameters:
    lst (list): The original list of elements.
    n (int): The number of elements to extract from the end.

    Returns:
    list: A new list containing the last n elements.
    """
    # Start at -n (n positions from the end) and go to the end
    return lst[-n:]

my_list = [1, 2, 3, 4, 5]
n_value = 2
result = get_last_n(my_list, n_value)

print(f"Original: {my_list}")
print(f"Last {n_value} elements: {result}")

Original: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


In [12]:
def reverse_skip(lst):
    """
    Extracts every second element starting from the second-to-last, moving backward.

    Parameters:
    lst (list): The original list of elements.

    Returns:
    list: A new list starting from index -2, moving backward by 2.
    """
    # Start at -2 (second-to-last), stop at the beginning, step of -2
    return lst[-2::-2]

my_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(my_list)

print(f"Original: {my_list}")
print(f"Result: {result}")

Original: [1, 2, 3, 4, 5, 6]
Result: [5, 3, 1]


### Exercise on Nested List

In [13]:
def flatten(lst):
    """
    Flattens a 2D nested list into a single-dimensional list.

    Parameters:
    lst (list): A list containing other lists as elements.

    Returns:
    list: A single list containing all elements from the sublists.
    """
    # This reads as: "take every 'item' inside every 'sublist' found in 'lst'"
    return [item for sublist in lst for item in sublist]

nested_list = [[1, 2], [3, 4], [5]]
flat_result = flatten(nested_list)

print(f"Original Nested List: {nested_list}")
print(f"Flattened List: {flat_result}")

Original Nested List: [[1, 2], [3, 4], [5]]
Flattened List: [1, 2, 3, 4, 5]


In [14]:
def access_nested_element(lst, indices):
    """
    Accesses a specific element in a nested list using a list of indices.

    Parameters:
    lst (list): The nested list (e.g., a list of lists).
    indices (list): A list of integers representing the path to the element.

    Returns:
    The element located at the specified indices.
    """
    # Start with the full nested list
    current_level = lst

    # Traverse through each index in the provided list
    for index in indices:
        current_level = current_level[index]

    return current_level

my_nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_indices = [1, 2]

result = access_nested_element(my_nested_list, my_indices)
print(f"The element at indices {my_indices} is: {result}")

The element at indices [1, 2] is: 6


In [15]:
def sum_nested(lst):
    """
    Calculates the sum of all numeric elements in a nested list of any depth.

    Parameters:
    lst (list): A nested list containing numbers or further nested lists.

    Returns:
    float/int: The total sum of all numbers found within the structure.
    """
    total = 0
    for item in lst:
        # Check if the item is a list itself
        if isinstance(item, list):
            # If it's a list, call the function again (Recursion)
            total += sum_nested(item)
        else:
            # If it's a number, add it to the total
            total += item
    return total

nested_data = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_data)

print(f"The total sum of {nested_data} is: {result}")

The total sum of [[1, 2], [3, [4, 5]], 6] is: 21


In [16]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from each sublist in a nested list.

    Parameters:
    lst (list): A nested list (list of lists).
    elem: The specific value to be removed from the sublists.

    Returns:
    list: A new nested list with the specified element removed.
    """
    # Outer comprehension goes through each sublist
    # Inner comprehension keeps 'x' only if it is NOT the element we want to remove
    return [[x for x in sublist if x != elem] for sublist in lst]

my_nested_list = [[1, 2], [3, 2], [4, 5]]
to_remove = 2

result = remove_element(my_nested_list, to_remove)
print(f"Original: {my_nested_list}")
print(f"Modified: {result}")

Original: [[1, 2], [3, 2], [4, 5]]
Modified: [[1], [3], [4, 5]]


In [17]:
def find_max_nested(lst):
    """
    Finds the maximum value in a nested list of any depth.

    Parameters:
    lst (list): A nested list containing numbers or further nested lists.

    Returns:
    float/int: The highest numeric value found within the structure.
    """
    # Initialize max_val as None or the first numeric element found
    max_val = float('-inf')  # Start with the smallest possible number

    for item in lst:
        if isinstance(item, list):
            # If it's a list, find the max of THAT list recursively
            inner_max = find_max_nested(item)
            if inner_max > max_val:
                max_val = inner_max
        else:
            # If it's a number, compare it to our current max_val
            if item > max_val:
                max_val = item

    return max_val

nested_data = [[1, 2], [3, [4, 5]], 6]
result = find_max_nested(nested_data)

print(f"The maximum element in {nested_data} is: {result}")

The maximum element in [[1, 2], [3, [4, 5]], 6] is: 6


In [18]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list (2D).

    Parameters:
    lst (list): A nested list containing sublists.
    elem: The specific value to be counted.

    Returns:
    int: The total number of times the element appears across all sublists.
    """
    # Count elem in each sublist and create a list of those counts, then sum them
    return sum(sublist.count(elem) for sublist in lst)

my_nested_list = [[1, 2], [2, 3], [2, 4]]
target_value = 2

result = count_occurrences(my_nested_list, target_value)
print(f"The element {target_value} appears {result} times.")

The element 2 appears 3 times.


In [19]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single-dimensional list.

    Parameters:
    lst (list): A list that can contain numbers or other nested lists.

    Returns:
    list: A single flat list containing all individual elements.
    """
    flat_list = []

    for item in lst:
        if isinstance(item, list):
            # If the item is a list, recursively flatten it and extend our result
            flat_list.extend(deep_flatten(item))
        else:
            # If the item is not a list (it's a number), just add it
            flat_list.append(item)

    return flat_list

nested_data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_data)

print(f"Original: {nested_data}")
print(f"Deeply Flattened: {result}")

Original: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Deeply Flattened: [1, 2, 3, 4, 5, 6, 7, 8]


In [20]:
def average_nested(lst):
    """
    Calculates the average of all elements in a 2D nested list.

    Parameters:
    lst (list): A nested list containing sublists of numbers.

    Returns:
    float: The arithmetic mean of all numbers in the nested structure.
    """
    # Step 1: Flatten the 2D list into a single list of numbers
    flat_list = [item for sublist in lst for item in sublist]

    # Step 2: Handle empty list to avoid division by zero
    if not flat_list:
        return 0.0

    # Step 3: Calculate average (Sum / Count)
    return sum(flat_list) / len(flat_list)

nested_numbers = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_numbers)

print(f"The average of {nested_numbers} is: {result}")

The average of [[1, 2], [3, 4], [5, 6]] is: 3.5


# To Do NumPy

## Problem-1

In [21]:
import numpy as np

# Initialize an empty array with size 2x2.
# Note: np.empty doesn't set values to 0; it contains whatever
# garbage data was in memory at the time.
empty_arr = np.empty((2, 2))

# Initialize an all-one array with size 4x2.
ones_arr = np.ones((4, 2))

# Return a new array of given shape and type, filled with a fill value.
# Example: Shape (3, 3) filled with the number 7.
full_arr = np.full((3, 3), 7)

# Return a new array of zeros with the same shape and type as a given array.
# Let's use full_arr as the reference.
zeros_like_arr = np.zeros_like(full_arr)

# Return a new array of ones with the same shape and type as a given array.
ones_like_arr = np.ones_like(full_arr)

# Convert an existing list to a numpy array.
new_list = [1, 2, 3, 4]
numpy_conversion = np.array(new_list)

print("1. Empty 2x2:\n", empty_arr)
print("\n2. Ones 4x2:\n", ones_arr)
print("\n3. Full (7s) 3x3:\n", full_arr)
print("\n4. Zeros Like (3x3):\n", zeros_like_arr)
print("\n5. Ones Like (3x3):\n", ones_like_arr)
print("\n6. List to Array:", numpy_conversion)

1. Empty 2x2:
 [[5.00509937e-315 0.00000000e+000]
 [6.72786719e-310 5.76851285e-317]]

2. Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full (7s) 3x3:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like (3x3):
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones Like (3x3):
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. List to Array: [1 2 3 4]


In [24]:
# Create an array with values ranging from 10 to 49
range_arr = np.arange(10, 50)
print("1. Range Array (10-49):\n", range_arr)

# Create a 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix (0-8):\n", matrix_3x3)

# Create a 3X3 identity matrix
identity_mat = np.eye(3)
print("\n3. 3x3 Identity Matrix:\n", identity_mat)

# Create a random array of size 30 and find the mean
rand_arr_30 = np.random.random(30)
print("\n4. Random Array (Size 30) Mean:", rand_arr_30.mean())

# Create a 10X10 array with random values and find min/max
rand_10x10 = np.random.random((10, 10))
print(f"\n5. 10x10 Random Array - Min: {rand_10x10.min():.4f}, Max: {rand_10x10.max():.4f}")

# Create a zero array of size 10 and replace 5th element with 1
zeros_10 = np.zeros(10)
zeros_10[4] = 1 # Index 4 is the 5th element
print("\n6. Zero array with 5th element as 1:\n", zeros_10)

# Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed Array:", reversed_arr)

# Create a 2d array with 1 on border and 0 inside (5x5 example)
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n8. 5x5 Border Array (1s on border, 0s inside):\n", border_arr)

# Create a 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Rows 1,3,5,7; Cols 0,2,4,6
checkerboard[::2, 1::2] = 1  # Rows 0,2,4,6; Cols 1,3,5,7
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard)

1. Range Array (10-49):
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix (0-8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array (Size 30) Mean: 0.47635822402646594

5. 10x10 Random Array - Min: 0.0183, Max: 0.9956

6. Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array: [0 4 0 0 2 1]

8. 5x5 Border Array (1s on border, 0s inside):
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
# Initializing the arrays provided in the problem
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Add the two arrays (x and y)
add_result = np.add(x, y) # Or simply x + y

# Subtract the two arrays (x and y)
sub_result = np.subtract(x, y) # Or simply x - y

# Multiply the array with an integer (choosing 3)
mult_result = x * 3

# Find the square of each element of the array
square_result = np.square(x)

# Find the dot products
dot_vw = np.dot(v, w)  # Vector-Vector: (9*11) + (10*12)
dot_xv = np.dot(x, v)  # Matrix-Vector
dot_xy = np.dot(x, y)  # Matrix-Matrix (Standard Matrix Multiplication)

# Concatenate x and y along row, and v and w along column
# Along rows (stacking one on top of the other)
concat_xy_row = np.vstack((x, y))
# Along columns for vectors (stacking side-by-side)
concat_vw_col = np.column_stack((v, w))

print("1. Addition (x+y):\n", add_result)
print("\n2. Subtraction (x-y):\n", sub_result)
print("\n3. Scalar Multiplication (x*3):\n", mult_result)
print("\n4. Square of x:\n", square_result)
print("\n5. Dot Products:\n v·w:", dot_vw, "\n x·v:", dot_xv, "\n x·y:\n", dot_xy)
print("\n6. Concatenation:\n xy (Row):\n", concat_xy_row, "\n vw (Col):\n", concat_vw_col)

# Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print(f"\n7. Error Concatenating x and v: {e}")

1. Addition (x+y):
 [[ 6  8]
 [10 13]]

2. Subtraction (x-y):
 [[-4 -4]
 [-4 -3]]

3. Scalar Multiplication (x*3):
 [[ 3  6]
 [ 9 15]]

4. Square of x:
 [[ 1  4]
 [ 9 25]]

5. Dot Products:
 v·w: 219 
 x·v: [29 77] 
 x·y:
 [[19 22]
 [50 58]]

6. Concatenation:
 xy (Row):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]] 
 vw (Col):
 [[ 9 11]
 [10 12]]

7. Error Concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [26]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Prove A · A_inv = I (Identity Matrix)
A_inv = np.linalg.inv(A)
I_result = np.dot(A, A_inv)
I_expected = np.eye(2)
proof1 = np.allclose(I_result, I_expected)
print(f"1. A * A_inv is Identity Matrix: {proof1}")
print(I_result)

# Prove AB != BA (Matrix multiplication is not commutative)
AB = np.dot(A, B)
BA = np.dot(B, A)
proof2 = not np.allclose(AB, BA)
print(f"\n2. AB is NOT equal to BA: {proof2}")
print("AB:\n", AB, "\nBA:\n", BA)

# Prove (AB).T = B.T · A.T (Transpose of a product)
lhs = (np.dot(A, B)).T
rhs = np.dot(B.T, A.T)
proof3 = np.allclose(lhs, rhs)
print(f"\n3. (AB).T == B.T * A.T: {proof3}")

1. A * A_inv is Identity Matrix: True
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB is NOT equal to BA: True
AB:
 [[23 13]
 [51 29]] 
BA:
 [[36 44]
 [13 16]]

3. (AB).T == B.T * A.T: True


### Experiment: How Fast is Numpy?

In [28]:
import time

# Set the size of the arrays
size = 1_000_000

# Python List Implementation
# Create two lists of 1 million elements each
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
# Element-wise addition using a list comprehension
list_result = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

python_time = end_time - start_time
print(f"Python List Addition Time: {python_time:.6f} seconds")

# NumPy Array Implementation
# Create two NumPy arrays of 1 million elements each
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
# Element-wise addition using NumPy's vectorized operation
array_result = array1 + array2
end_time = time.time()

numpy_time = end_time - start_time
print(f"NumPy Array Addition Time: {numpy_time:.6f} seconds")

print(f"\nNumPy is approximately {python_time / numpy_time:.2f}x faster than Python lists!")

Python List Addition Time: 0.172558 seconds
NumPy Array Addition Time: 0.007546 seconds

NumPy is approximately 22.87x faster than Python lists!


In [30]:
# Set the size to 1,000,000
size = 1_000_000

# --- 1. Python List Implementation ---
# Create two lists of 1 million elements each
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
# Element-wise multiplication using zip and list comprehension
list_result = [a * b for a, b in zip(list1, list2)]
end_time = time.time()

python_time = end_time - start_time
print(f"Python List Multiplication Time: {python_time:.6f} seconds")

# --- 2. NumPy Array Implementation ---
# Create two NumPy arrays of 1 million elements each
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
# Element-wise multiplication using NumPy's vectorized operation
array_result = array1 * array2
end_time = time.time()

numpy_time = end_time - start_time
print(f"NumPy Array Multiplication Time: {numpy_time:.6f} seconds")

print(f"\nNumPy is approximately {python_time / numpy_time:.2f}x faster!")

Python List Multiplication Time: 0.083692 seconds
NumPy Array Multiplication Time: 0.002880 seconds

NumPy is approximately 29.06x faster!


In [31]:
import numpy as np
import time

# Set the size to 1,000,000
size = 1_000_000

# --- 1. Python List Implementation ---
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
# Standard way to compute dot product: sum of element-wise products
dot_product_python = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()

python_time = end_time - start_time
print(f"Python List Dot Product Time: {python_time:.6f} seconds")

# --- 2. NumPy Array Implementation ---
# Using int64 to avoid overflow with large products
array1 = np.arange(size, dtype=np.int64)
array2 = np.arange(size, dtype=np.int64)

start_time = time.time()
# Using the built-in np.dot function
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()

numpy_time = end_time - start_time
print(f"NumPy Array Dot Product Time: {numpy_time:.6f} seconds")

print(f"\nNumPy is approximately {python_time / numpy_time:.2f}x faster!")

Python List Dot Product Time: 0.090600 seconds
NumPy Array Dot Product Time: 0.001791 seconds

NumPy is approximately 50.57x faster!


In [32]:
# --- 1. Python List Implementation ---
size = 200 # Using 200 to keep the execution time reasonable
A_list = [[i for i in range(size)] for j in range(size)]
B_list = [[i for i in range(size)] for j in range(size)]

start_time = time.time()
# Manual nested loops (Triple for-loop)
result_list = [[0 for _ in range(size)] for _ in range(size)]
for i in range(size):
    for j in range(size):
        for k in range(size):
            result_list[i][j] += A_list[i][k] * B_list[k][j]
end_time = time.time()

python_time = end_time - start_time
print(f"Python List (200x200) Time: {python_time:.4f} seconds")

# --- 2. NumPy Array Implementation ---
size_np = 1000
A_np = np.random.rand(size_np, size_np)
B_np = np.random.rand(size_np, size_np)

start_time = time.time()
# Using np.dot() or the @ operator
result_np = np.dot(A_np, B_np)
end_time = time.time()

numpy_time = end_time - start_time
print(f"NumPy Array (1000x1000) Time: {numpy_time:.4f} seconds")

Python List (200x200) Time: 2.6031 seconds
NumPy Array (1000x1000) Time: 0.0711 seconds
